# Utiliser une image de base Ubuntu
FROM ubuntu:20.04

# Définir les variables d'environnement pour éviter les invites interactives
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

# Installer les paquets nécessaires
RUN apt-get update && apt-get install -y \
    vlc \
    && rm -rf /var/lib/apt/lists/*

# Créer un utilisateur non-root
RUN useradd -m vlcuser

# Copier les fichiers nécessaires
COPY test.mp4 /home/vlcuser/test.mp4
COPY start.sh /start.sh

# Changer les permissions des fichiers copiés
RUN chown vlcuser:vlcuser /home/vlcuser/test.mp4

# Rendre le script de démarrage exécutable
RUN chmod +x /start.sh

# Exposer le port RTSP
EXPOSE 8554

# Exécuter le script de démarrage
USER vlcuser
CMD ["/bin/sh", "/start.sh"]
