# playbook_asterisk.yml
- hosts: all
  become: yes
  tasks:
    - name: Pull Asterisk Docker image
      docker_image:
        name: asterisk
        build: ./path_to_asterisk_dockerfile_directory

    - name: Run Asterisk container
      docker_container:
        name: asterisk
        image: asterisk
        state: started
        ports:
          - "5060:5060"
          - "5061:5061"
          - "10000-20000:10000-20000/udp"
